// <copyright file="UDPMulticastTest.Receive.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace SmallTuba.Network.UDP
{
    public partial class UDPMulticastTest
    {
[TestMethod]
[PexGeneratedBy(typeof(UDPMulticastTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void Receive153()
{
    UDPMulticast uDPMulticast;
    object o;
    uDPMulticast = new UDPMulticast(0);
    o = this.Receive(uDPMulticast, 0L);
}
    }
}
